work/cricket/config/routes.rb
Cricket::Application.routes.draw do
  resources :scores

  resources :managers

  resources :palyers

  resources :teams

  resources :matches

  root "pages#index"

end

work/cricket/app/models/score.rb
class Score < ActiveRecord::Base
	belongs_to :match
	belongs_to :palyer
end

work/cricket/app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render action: 'show', status: :created, location: @score }
      else
        format.html { render action: 'new' }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def score_params
      params.require(:score).permit(:total_score, :wickets, :highest_score, :match_id, :palyer_id)
    end
end

work/cricket/app/helpers/scores_helper.rb
module ScoresHelper
end

work/cricket/app/views/scores/_form.html.erb
<%= form_for(@score) do |f| %>
  <% if @score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
      <% @score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :total_score %><br>
    <%= f.number_field :total_score %>
  </div>
  <div class="field">
    <%= f.label :wickets %><br>
    <%= f.number_field :wickets %>
  </div>
  <div class="field">
    <%= f.label :highest_score %><br>
    <%= f.number_field :highest_score %>
  </div>
  <div class="field">
    <%= f.label :player_name %><br>
    <%= f.select :palyer_id, options_from_collection_for_select(Palyer.all, 'id', 'player_name') %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

work/cricket/app/views/scores/edit.html.erb
<h1>Editing score</h1>

<%= render 'form' %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

work/cricket/app/views/scores/index.html.erb
<h1>Listing scores</h1>

<table>
  <thead>
    <tr>
      <th>Total score</th>
      <th>Wickets</th>
      <th>Highest score</th>
      <th>Player</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= score.total_score %></td>
        <td><%= score.wickets %></td>
        <td><%= score.highest_score %></td>
        <td><%= score.palyer.player_name %></td>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>

work/cricket/app/views/scores/new.html.erb
<h1>New score</h1>

<%= render 'form' %>

<%= link_to 'Back', scores_path %>

work/cricket/app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Total score:</strong>
  <%= @score.total_score %>
</p>

<p>
  <strong>Wickets:</strong>
  <%= @score.wickets %>
</p>

<p>
  <strong>Highest score:</strong>
  <%= @score.highest_score %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>