work/cricket/config/routes.rb
Cricket::Application.routes.draw do
  resources :scores

  resources :managers

  resources :palyers

  resources :teams

  resources :matches

  root "pages#index"

end

work/cricket/app/models/manager.rb
class Manager < ActiveRecord::Base
	belongs_to :team
	validates :manager_name, presence: :true
	validates_length_of :manager_name, :within => 6..12
	validates_format_of :manager_name, :with => /\w+/
end

work/cricket/app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :set_manager, only: [:show, :edit, :update, :destroy]

  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.all
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
  end

  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(manager_params)

    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: 'Manager was successfully created.' }
        format.json { render action: 'show', status: :created, location: @manager }
      else
        format.html { render action: 'new' }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1
  # PATCH/PUT /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to @manager, notice: 'Manager was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to managers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manager_params
      params.require(:manager).permit(:manager_name, :team_id)
    end
end

work/cricket/app/helpers/managers_helper.rb
module ManagersHelper
end

work/cricket/app/views/managers/_form.html.erb
<%= form_for(@manager) do |f| %>
  <% if @manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

      <ul>
      <% @manager.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :team_name %><br>
    <%= f.select :team_id, options_from_collection_for_select(Team.all, 'id', 'name') %>
  </div>
  <div class="field">
    <%= f.label :manager_name %><br>
    <%= f.text_field :manager_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

work/cricket/app/views/managers/edit.html.erb
<h1>Editing manager</h1>

<%= render 'form' %>

<%= link_to 'Show', @manager %> |
<%= link_to 'Back', managers_path %>

work/cricket/app/views/managers/index.html.erb
<h1>Listing managers</h1>

<table>
  <thead>
    <tr>
      <th>Team Name</th>
      <th>Manager name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @managers.each do |manager| %>
      <tr>
        <td><%= manager.team.name %></td>
        <td><%= manager.manager_name %></td>
        <td><%= link_to 'Show', manager %></td>
        <td><%= link_to 'Edit', edit_manager_path(manager) %></td>
        <td><%= link_to 'Destroy', manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manager', new_manager_path %>

work/cricket/app/views/managers/new.html.erb
<h1>New manager</h1>

<%= render 'form' %>

<%= link_to 'Back', managers_path %>

work/cricket/app/views/managers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Manager name:</strong>
  <%= @manager.team.name %>
</p>
<p>
  <strong>Manager name:</strong>
  <%= @manager.manager_name %>
</p>
	
<%= link_to 'Edit', edit_manager_path(@manager) %> |
<%= link_to 'Back', managers_path %>