work/cricket/config/routes.rb
Cricket::Application.routes.draw do
  resources :scores

  resources :managers

  resources :palyers

  resources :teams

  resources :matches

  root "pages#index"

end

work/cricket/app/models/match.rb
class Match < ActiveRecord::Base
	#belongs_to :home_team, class_name: "Team", foreign_key: "team_home" 
	#belongs_to :away_team, class_name: "Team", foreign_key: "team_away"
  belongs_to :team
	has_many :scores
end

work/cricket/app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render action: 'show', status: :created, location: @match }
      else
        format.html { render action: 'new' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:team_home, :team_away, :team_id, :total_score )
    end
end

work/cricket/app/helpers/matches_helper.rb
module MatchesHelper
end

work/cricket/app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div> 
  <% end %>
  <div class="field">
    <%= f.label :team_home %><br>
    <%= f.text_field :team_home %>
  </div>
  <div class="field">
    <%= f.label :team_away %><br>
    <%= f.text_field :team_away %>
  </div>

  <div class="field">
  <%= f.label :team_away %>
  <%= f.select :team_id, options_from_collection_for_select(Team.all, 'id' 'name') %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

work/cricket/app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

work/cricket/app/views/matches/index.html.erb
<h1>Listing matches</h1>

<table>
  <thead>
    <tr>
      <th>Team home</th>
      <th>Team away</th>
      <th>Team home-1</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.team_home %></td>
        <td><%= match.team_away %></td>
        <td><%= match.team.team_name %></td>
        <td><%= link_to 'Show', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

work/cricket/app/views/matches/new.html.erb
<h1>New match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

work/cricket/app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team home:</strong>
  <%= @match.team_home %>
</p>

<p>
  <strong>Team away:</strong>
  <%= @match.team_away %>
</p>


<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>