work/cricket/config/routes.rb
Cricket::Application.routes.draw do
  resources :scores

  resources :managers

  resources :palyers

  resources :teams

  resources :matches

  root "pages#index"

end

work/cricket/app/models/palyer.rb
class Palyer < ActiveRecord::Base
	has_many :scores
  belongs_to :team

	validates :player_name, presence: true
	validates :score, presence: true
	validates :team_id, presence: true
	validates_length_of :player_name, :within => 6..12
	validates_format_of :player_name, :with => /\w+/
	validates_numericality_of :score, :only_integer => true
	validates_length_of :score, :within => 0..3	
end

work/cricket/app/controllers/palyers_controller.rb
class PalyersController < ApplicationController
  before_action :set_palyer, only: [:show, :edit, :update, :destroy]

  # GET /palyers
  # GET /palyers.json
  def index
    @palyers = Palyer.all
  end

  # GET /palyers/1
  # GET /palyers/1.json
  def show
  
  end

  # GET /palyers/new
  def new
    @palyer = Palyer.new
  end

  # GET /palyers/1/edit
  def edit
  end

  # POST /palyers
  # POST /palyers.json
  def create
    @palyer = Palyer.new(palyer_params)

    respond_to do |format|
      if @palyer.save
        format.html { redirect_to @palyer, notice: 'Palyer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @palyer }
      else
        format.html { render action: 'new' }
        format.json { render json: @palyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /palyers/1
  # PATCH/PUT /palyers/1.json
  def update
    respond_to do |format|
      if @palyer.update(palyer_params)
        format.html { redirect_to @palyer, notice: 'Palyer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @palyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /palyers/1
  # DELETE /palyers/1.json
  def destroy
    @palyer.destroy
    respond_to do |format|
      format.html { redirect_to palyers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_palyer
      @palyer = Palyer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def palyer_params
      params.require(:palyer).permit(:player_name, :score, :team_id)
    end
end

work/cricket/app/helpers/palyers_helper.rb
module PalyersHelper
end

work/cricket/app/views/palyers/_form.html.erb
<%= form_for(@palyer) do |f| %>
  <% if @palyer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@palyer.errors.count, "error") %> prohibited this palyer from being saved:</h2>
      <ul>
      <% @palyer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="field">
    <%= f.label :team_name %><br>
    <%= f.select :team_id, options_from_collection_for_select(Team.all, 'id', 'name')  %>
  </div>
  


  <div class="field">
    <%= f.label :player_name %><br>
    <%= f.text_field :player_name %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.text_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

work/cricket/app/views/palyers/edit.html.erb
<h1>Editing palyer</h1>

<%= render 'form' %>

<%= link_to 'Show', @palyer %> |
<%= link_to 'Back', palyers_path %>

work/cricket/app/views/palyers/index.html.erb
<h1>Listing palyers</h1>

<table>
  <thead>
    <tr>
      <th>Team Name</th>
      <th>Player name</th>
      <th>Score</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @palyers.each do |palyer| %>
      <tr>
        <td><%= palyer.team.name %></td>
        <td><%= palyer.player_name %></td>
        <td><%= palyer.score %></td>
        <td><%= link_to 'Show', palyer %></td>
        <td><%= link_to 'Edit', edit_palyer_path(palyer) %></td>
        <td><%= link_to 'Destroy', palyer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Palyer', new_palyer_path %>

work/cricket/app/views/palyers/new.html.erb
<h1>New palyer</h1>

<%= render 'form' %>

<%= link_to 'Back', palyers_path %>

work/cricket/app/views/palyers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team name:</strong>
  <%= @palyer.team.name %>
</p>


<p>
  <strong>Player name:</strong>
  <%= @palyer.player_name %>
</p>

<p>
  <strong>Score:</strong>
  <%= @palyer.score %>
</p>

<%= link_to 'Edit', edit_palyer_path(@palyer) %> |
<%= link_to 'Back', palyers_path %>